-- Which board this bucket's images are packed/dithered for (e.g.
-- 'ee02-13in3', 'ee04-7in3') - see lib/media-constants.ts's BoardId/
-- BOARD_GEOMETRY. The encrypted image pipeline bakes pixels for one fixed
-- resolution per bucket at upload time (the Worker never sees plaintext to
-- re-render at a different resolution later - see root CLAUDE.md's
-- encrypted-buckets plan), so unlike device_buckets (many devices per
-- bucket is fine), a bucket can't straddle two boards with different screen
-- geometries. Set once at bucket creation (routes/admin/buckets.ts) and
-- immutable after - changing it would mean re-deriving every image's
-- packed/thumbnail bytes from its stored raw original, the same cost as a
-- key rotation but for a reason key rotation doesn't cover.
--
-- Defaults every pre-existing bucket to 'ee02-13in3' - the only board the
-- image pipeline supported before this migration, so every image already
-- stored was in fact packed at that geometry regardless of what a bucket
-- row said before this column existed.
ALTER TABLE buckets ADD COLUMN target_board TEXT NOT NULL DEFAULT 'ee02-13in3';
